[package]
name = "fixt_test"
version.workspace = true
description = "tests the fixturator macros in an external crate"
license = "Apache-2.0"
repository.workspace = true
documentation = "https://docs.rs/fixt_test"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
keywords = ["holochain", "holo", "test", "fixture"]
categories = ["fixtures"]
edition = "2021"
publish = false

[dependencies]
fixt = { workspace = true }
paste = "1.0.12"
